Repository AY2122S1-CS2113T-T10-2/tp, pull requests merged in 2021-11, with the labels that each got.

#184 Update Developer Guide
  docs/DeveloperGuide.md
  docs/attachments/ActiveRecallCreateEnvironmentSequenceDiagram.png
  docs/attachments/ActiveRecallGetFeedbackSequence.png
  docs/attachments/ActiveRecallSequenceDiagram.png
  docs/attachments/ActiveRecallShowQuestionSequence.png
  docs/attachments/ActiveRecallUpdateQuestionDifficultySequence.png
  docs/uml/ActiveRecallSequenceDiagram.puml
  docs/uml/activerecall/ActiveRecallCreateEnvironmentSequenceDiagram.puml
  docs/uml/activerecall/ActiveRecallGetFeedbackSequence.puml
  docs/uml/activerecall/ActiveRecallShowQuestionSequence.puml
  docs/uml/activerecall/ActiveRecallUpdateQuestionDifficultySequence.puml
Labels: type.Task, priority.Medium

#188 Fix PED Bugs and Address TA Code Review
  docs/UserGuide.md
  src/main/java/terminus/command/content/link/AddLinkCommand.java
Labels: priority.Medium

#186 Fix PE-D issues and refactor Terminus
  src/main/java/terminus/Terminus.java
  src/main/java/terminus/common/Messages.java
  src/main/java/terminus/content/Question.java
  src/test/java/terminus/TerminusTest.java
  src/test/java/terminus/command/QuestionCommandTest.java
  src/test/java/terminus/parser/QuestionCommandParserTest.java
Labels: type.Bug, severity.Medium

#187 Fix PE Bugs and Update IText 5 to IText7
  build.gradle
  src/main/java/terminus/command/Command.java
  src/main/java/terminus/command/GoCommand.java
  src/main/java/terminus/command/WorkspaceCommand.java
  src/main/java/terminus/common/CommonFormat.java
  src/main/java/terminus/storage/PdfStorage.java
  src/test/java/terminus/command/content/link/ViewLinkCommandTest.java
  src/test/java/terminus/command/content/note/AddNoteCommandTest.java
  src/test/java/terminus/parser/LinkCommandParserTest.java
  src/test/java/terminus/parser/MainCommandParserTest.java
  src/test/java/terminus/parser/ModuleCommandParserTest.java
  src/test/java/terminus/parser/ModuleWorkspaceCommandParserTest.java
  src/test/java/terminus/parser/NoteCommandParserTest.java
  src/test/java/terminus/parser/QuestionCommandParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Medium

#189 Reorganize User Guide
  docs/UserGuide.md
Labels: type.Task, type.Bug, priority.High

#191 Update DG include Architecture diagram
  docs/DeveloperGuide.md
  docs/attachments/ArchitectureDiagram.png
  docs/attachments/CommandClassDiagram.png
  docs/attachments/CommandDetailedClassDiagram.png
  docs/attachments/CommandExecution.png
  docs/attachments/Content.png
  docs/attachments/GoCommandExecution.png
  docs/attachments/MainExit.png
  docs/attachments/MainInit.png
  docs/attachments/MainLogic.png
  docs/attachments/Module.png
  docs/attachments/NoteCommandExecution.png
  docs/attachments/ParserClassDiagram.png
  docs/attachments/ParserDetailedClassDiagram.png
  docs/attachments/Terminus.png
  docs/uml/ArchitectureDiagram.puml
  docs/uml/ClassStyle.puml
  docs/uml/CommandClassDiagram.puml
  docs/uml/CommandDetailedClassDiagram.puml
  docs/uml/CommandExecution.puml
  docs/uml/Content.puml
  docs/uml/GoCommandExecution.puml
  docs/uml/MainExit.puml
  docs/uml/MainInit.puml
  docs/uml/MainLogic.puml
  docs/uml/Module.puml
  docs/uml/NoteCommandExecution.puml
  docs/uml/ParserClassDiagram.puml
  docs/uml/ParserDetailedClassDiagram.puml
  docs/uml/SequenceStyle.puml
  docs/uml/Terminus.puml
Labels: type.Task, priority.High, severity.Low

#192 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/attachments/ConflictManagerSequenceDiagram.png
  docs/team/louislouis19.md
  docs/uml/ConflictManagerSequenceDiagram.puml
  src/main/java/terminus/common/CommonFormat.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#190 Update DG Storage Components and Implementation
  docs/DeveloperGuide.md
  docs/attachments/ActiveRecallClassDiagram.png
  docs/attachments/ActiveRecallCreateEnvironmentSequenceDiagram.png
  docs/attachments/ActiveRecallGetFeedbackSequence.png
  docs/attachments/ActiveRecallSequenceDiagram.png
  docs/attachments/ActiveRecallShowQuestionSequence.png
  docs/attachments/ActiveRecallUpdateQuestionDifficultySequence.png
  docs/attachments/AddingContentSequenceDiagram.png
  docs/attachments/ConflictManagerSequenceDiagram.png
  docs/attachments/DeletingContentSequenceDiagram.png
  docs/attachments/StorageCommandResultSequenceDiagram.png
  docs/attachments/StorageComponent.png
  docs/attachments/StorageInitializeSequenceDiagram.png
  docs/attachments/StorageLoadSequenceDiagram_part1.png
  docs/attachments/StorageLoadSequenceDiagram_part2.png
  docs/attachments/TimetableSequenceDiagram.png
  docs/attachments/UIClassDiagram.png
  docs/uml/ActiveRecallClassDiagram.puml
  docs/uml/ActiveRecallSequenceDiagram.puml
  docs/uml/ConflictManagerSequenceDiagram.puml
  docs/uml/TimetableSequenceDiagram.puml
  docs/uml/UIClassDiagram.puml
  docs/uml/activerecall/ActiveRecallCreateEnvironmentSequenceDiagram.puml
  docs/uml/activerecall/ActiveRecallGetFeedbackSequence.puml
  docs/uml/activerecall/ActiveRecallShowQuestionSequence.puml
  docs/uml/activerecall/ActiveRecallUpdateQuestionDifficultySequence.puml
  docs/uml/content/AddingContentSequenceDiagram.puml
  docs/uml/content/DeletingContentSequenceDiagram.puml
  docs/uml/storage/AddModuleStorage.puml
  docs/uml/storage/AddNoteCommand_Storage_SequenceDiagram.puml
  docs/uml/storage/DeleteModuleCommand_Storage_SequenceDiagram.puml
  docs/uml/storage/Storage.puml
  docs/uml/storage/StorageCommandResultSequenceDiagram.puml
  docs/uml/storage/StorageInitializeSequenceDiagram.puml
  docs/uml/storage/StorageInitializeSequenceDiagram_old.puml
  docs/uml/storage/StorageLoadSequenceDiagram_part1.puml
  docs/uml/storage/StorageLoadSequenceDiagram_part2.puml
  src/main/java/terminus/Terminus.java
  src/main/java/terminus/storage/NoteStorage.java
  src/main/java/terminus/storage/StorageManager.java
  src/test/java/terminus/storage/NoteStorageTest.java
Labels: type.Task

#194 Add Project Portfolio page
  docs/AboutUs.md
  docs/team/kelvneo.md
Labels: type.Task

#196 Add my ppp
  docs/team/woolicious98.md
Labels: type.Task

#193 Update error msg and fix to include depdencies for IText 7
  build.gradle
  docs/DeveloperGuide.md
  docs/attachments/CommandExecution.png
  docs/team/3m0W33D.md
  docs/uml/CommandExecution.puml
  src/main/java/terminus/Terminus.java
  src/main/java/terminus/command/module/DeleteModuleCommand.java
  src/main/java/terminus/command/module/UpdateModuleCommand.java
  src/main/java/terminus/common/Messages.java
  src/main/java/terminus/content/ContentManager.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#198 Fix bug in filtermanager
  src/main/java/terminus/storage/FilterManager.java
Labels: type.Bug

#199 Update filtermanager with more cases
  src/main/java/terminus/Terminus.java
  src/main/java/terminus/common/Messages.java
  src/main/java/terminus/storage/FilterManager.java
  src/main/java/terminus/storage/Storage.java
  src/main/java/terminus/storage/StorageManager.java
  src/test/java/terminus/storage/FilterManagerTest.java
  src/test/resources/incorrectFile.json
Labels: type.Task, type.Bug, priority.High

#203 Update UG to provide some name restriction
  docs/UserGuide.md
  src/main/java/terminus/Terminus.java
Labels: type.Task, severity.VeryLow

#206 Update Sequence Diagram
  docs/DeveloperGuide.md
  docs/attachments/ConflictManagerSequenceDiagram.png
  docs/attachments/TimetableGetDailySchedule.png
  docs/attachments/TimetableSequenceDiagram.png
  docs/uml/ConflictManagerSequenceDiagram.puml
  docs/uml/TimetableGetDailySchedule.puml
  docs/uml/TimetableSequenceDiagram.puml
Labels: priority.Medium

#213 Change Logger error behaviour and separate StorageManager from Logger
  src/main/java/terminus/Terminus.java
  src/test/java/terminus/TerminusTest.java
Labels: type.Bug, severity.High
