Repository AY2122S1-CS2113T-T10-2/tp, pull requests merged in 2021-10, with the labels that each got.

#56 Add unit testing for MainCommandParser
  src/test/java/terminus/TerminusTest.java
  src/test/java/terminus/parser/MainCommandParserTest.java
Labels: type.Task, priority.High

#53 Merge branch-notes to master
  src/main/java/terminus/Terminus.java
  src/main/java/terminus/command/BackCommand.java
  src/main/java/terminus/command/Command.java
  src/main/java/terminus/command/DeleteCommand.java
  src/main/java/terminus/command/ExitCommand.java
  src/main/java/terminus/command/HelpCommand.java
  src/main/java/terminus/command/NotesCommand.java
  src/main/java/terminus/command/ViewCommand.java
  src/main/java/terminus/command/WorkspaceCommand.java
  src/main/java/terminus/command/note/AddCommand.java
  src/main/java/terminus/common/CommonFormat.java
  src/main/java/terminus/common/Messages.java
  src/main/java/terminus/content/Content.java
  src/main/java/terminus/content/ContentManager.java
  src/main/java/terminus/content/Note.java
  src/main/java/terminus/module/NusModule.java
  src/main/java/terminus/parser/CommandParser.java
  src/main/java/terminus/parser/MainCommandParser.java
  src/main/java/terminus/parser/NoteCommandParser.java
  src/test/java/terminus/parser/MainCommandParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Epic, type.Story, priority.High, severity.High

#72 Update forgotten delete testcase
  src/test/java/terminus/command/note/DeleteNoteCommandTest.java
Labels: type.Task, type.Bug, priority.High, severity.VeryLow

#79 Add JUnit test for ContentManager and NusModule
  src/test/java/terminus/content/ContentManagerTest.java
  src/test/java/terminus/module/NusModuleTest.java
Labels: type.Task, priority.High

#78 Command and Command Parser logging
  src/main/java/terminus/command/BackCommand.java
  src/main/java/terminus/command/DeleteCommand.java
  src/main/java/terminus/command/ExitCommand.java
  src/main/java/terminus/command/HelpCommand.java
  src/main/java/terminus/command/ViewCommand.java
  src/main/java/terminus/command/WorkspaceCommand.java
  src/main/java/terminus/parser/CommandParser.java
Labels: type.Task, priority.High, severity.Low

#81 Add logging to AddNoteCommand, NusModule
  src/main/java/terminus/command/note/AddNoteCommand.java
  src/main/java/terminus/content/ContentManager.java
  src/main/java/terminus/module/NusModule.java
Labels: type.Task, priority.High, severity.Low

#99 Update singleton methods
  src/main/java/terminus/common/CommonFormat.java
  src/main/java/terminus/parser/LinkCommandParser.java
  src/main/java/terminus/parser/MainCommandParser.java
  src/main/java/terminus/parser/ModuleCommandParser.java
  src/main/java/terminus/parser/ModuleWorkspaceCommandParser.java
  src/main/java/terminus/parser/NoteCommandParser.java
Labels: type.Enhancement, type.Task, priority.Low, severity.Low

#101 Implement view weekly and daily Timetable
  src/main/java/terminus/command/TimetableCommand.java
  src/main/java/terminus/common/CommonFormat.java
  src/main/java/terminus/common/CommonUtils.java
  src/main/java/terminus/common/DaysOfWeekEnum.java
  src/main/java/terminus/common/Messages.java
  src/main/java/terminus/parser/MainCommandParser.java
  src/main/java/terminus/timetable/Timetable.java
  src/test/java/terminus/command/TimetableCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.High

#95 Update note to be save as text file
  src/main/java/terminus/Terminus.java
  src/main/java/terminus/command/Command.java
  src/main/java/terminus/command/GoCommand.java
  src/main/java/terminus/command/WorkspaceCommand.java
  src/main/java/terminus/command/content/DeleteCommand.java
  src/main/java/terminus/command/content/InnerModuleCommand.java
  src/main/java/terminus/command/content/note/AddNoteCommand.java
  src/main/java/terminus/command/content/note/DeleteNoteCommand.java
  src/main/java/terminus/command/module/AddModuleCommand.java
  src/main/java/terminus/command/module/DeleteModuleCommand.java
  src/main/java/terminus/common/CommonFormat.java
  src/main/java/terminus/common/CommonUtils.java
  src/main/java/terminus/common/Messages.java
  src/main/java/terminus/content/ContentManager.java
  src/main/java/terminus/module/NusModule.java
  src/main/java/terminus/parser/LinkCommandParser.java
  src/main/java/terminus/parser/MainCommandParser.java
  src/main/java/terminus/parser/ModuleCommandParser.java
  src/main/java/terminus/parser/ModuleWorkspaceCommandParser.java
  src/main/java/terminus/parser/NoteCommandParser.java
  src/main/java/terminus/storage/ModuleStorage.java
  src/test/java/terminus/TestFilePath.java
  src/test/java/terminus/command/ExitCommandTest.java
  src/test/java/terminus/command/GoCommandTest.java
  src/test/java/terminus/command/HelpCommandTest.java
  src/test/java/terminus/command/ModuleCommandTest.java
  src/test/java/terminus/command/NoteCommandTest.java
  src/test/java/terminus/command/ScheduleCommandTest.java
  src/test/java/terminus/command/TimetableCommandTest.java
  src/test/java/terminus/command/content/link/AddLinkCommandTest.java
  src/test/java/terminus/command/content/link/BackLinkCommandTest.java
  src/test/java/terminus/command/content/link/DeleteLinkCommandTest.java
  src/test/java/terminus/command/content/link/ViewLinkCommandTest.java
  src/test/java/terminus/command/content/note/AddNoteCommandTest.java
  src/test/java/terminus/command/content/note/BackNoteCommandTest.java
  src/test/java/terminus/command/content/note/DeleteNoteCommandTest.java
  src/test/java/terminus/command/content/note/ViewNoteCommandTest.java
  src/test/java/terminus/command/module/AddModuleCommandTest.java
  src/test/java/terminus/command/module/DeleteModuleCommandTest.java
  src/test/java/terminus/command/module/ViewModuleCommandTest.java
  src/test/java/terminus/common/CommonUtilsTest.java
  src/test/java/terminus/parser/NoteCommandParserTest.java
  src/test/java/terminus/storage/ModuleStorageTest.java
  src/test/resources/saveFile.json
  src/test/resources/validFile.json
Labels: type.Story, type.Enhancement, priority.Medium, severity.High

#107 Update UG and DG to include Active Recall
  README.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/attachments/ActiveRecallClassDiagram.png
  docs/attachments/ActiveRecallSequenceDiagram.png
  docs/uml/ActiveRecallClassDiagram.puml
  docs/uml/ActiveRecallSequenceDiagram.puml
  src/main/java/terminus/activerecall/GameEnvironment.java
Labels: type.Task, priority.Medium

#144 Command Error messages fix and Refactoring
  src/main/java/terminus/activerecall/GameEnvironment.java
  src/main/java/terminus/command/BackCommand.java
  src/main/java/terminus/command/GoCommand.java
  src/main/java/terminus/command/content/DeleteCommand.java
  src/main/java/terminus/command/content/link/AddLinkCommand.java
  src/main/java/terminus/command/content/note/AddNoteCommand.java
  src/main/java/terminus/command/module/AddModuleCommand.java
  src/main/java/terminus/command/module/DeleteModuleCommand.java
  src/main/java/terminus/command/module/UpdateModuleCommand.java
  src/main/java/terminus/common/CommonFormat.java
  src/main/java/terminus/common/CommonUtils.java
  src/main/java/terminus/common/Messages.java
  src/test/java/terminus/command/content/link/AddLinkCommandTest.java
  src/test/java/terminus/command/content/note/AddNoteCommandTest.java
  src/test/java/terminus/command/content/question/AddQuestionCommandTest.java
  src/test/java/terminus/command/module/AddModuleCommandTest.java
  src/test/java/terminus/common/CommonUtilsTest.java
  src/test/java/terminus/parser/ModuleCommandParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Medium, severity.Medium

#143 SLAP file storage
  src/main/java/terminus/Terminus.java
  src/main/java/terminus/command/Command.java
  src/main/java/terminus/command/CommandResult.java
  src/main/java/terminus/command/GoCommand.java
  src/main/java/terminus/command/WorkspaceCommand.java
  src/main/java/terminus/command/content/DeleteCommand.java
  src/main/java/terminus/command/content/InnerModuleCommand.java
  src/main/java/terminus/command/content/note/AddNoteCommand.java
  src/main/java/terminus/command/content/note/DeleteNoteCommand.java
  src/main/java/terminus/command/content/note/ExportNoteCommand.java
  src/main/java/terminus/command/content/note/ReloadNoteCommand.java
  src/main/java/terminus/command/module/AddModuleCommand.java
  src/main/java/terminus/command/module/DeleteModuleCommand.java
  src/main/java/terminus/command/module/UpdateModuleCommand.java
  src/main/java/terminus/common/CommonUtils.java
  src/main/java/terminus/common/Messages.java
  src/main/java/terminus/exception/InvalidFileException.java
  src/main/java/terminus/storage/FilterManager.java
  src/main/java/terminus/storage/FolderStorage.java
  src/main/java/terminus/storage/JsonStorage.java
  src/main/java/terminus/storage/ModuleStorage.java
  src/main/java/terminus/storage/NoteStorage.java
  src/main/java/terminus/storage/PdfStorage.java
  src/main/java/terminus/storage/Storage.java
  src/main/java/terminus/storage/StorageActionEnum.java
  src/main/java/terminus/storage/StorageManager.java
  src/main/java/terminus/storage/StorageTypeEnum.java
  src/main/java/terminus/timetable/Timetable.java
  src/test/java/terminus/TestFilePath.java
  src/test/java/terminus/command/GoCommandTest.java
  src/test/java/terminus/command/ModuleCommandTest.java
  src/test/java/terminus/command/NoteCommandTest.java
  src/test/java/terminus/command/content/link/AddLinkCommandTest.java
  src/test/java/terminus/command/content/note/AddNoteCommandTest.java
  src/test/java/terminus/command/content/note/DeleteNoteCommandTest.java
  src/test/java/terminus/command/content/note/ExportNoteCommandTest.java
  src/test/java/terminus/command/content/note/ReloadNoteCommandTest.java
  src/test/java/terminus/command/content/note/ViewNoteCommandTest.java
  src/test/java/terminus/command/module/AddModuleCommandTest.java
  src/test/java/terminus/command/module/DeleteModuleCommandTest.java
  src/test/java/terminus/command/module/UpdateModuleCommandTest.java
  src/test/java/terminus/storage/FilterManagerTest.java
  src/test/java/terminus/storage/FolderStorageTest.java
  src/test/java/terminus/storage/JsonStorageTest.java
  src/test/java/terminus/storage/ModuleStorageTest.java
  src/test/java/terminus/storage/NoteStorageTest.java
  src/test/java/terminus/storage/PdfStorageTest.java
  src/test/java/terminus/storage/StorageManagerTest.java
  src/test/java/terminus/storage/StorageTest.java
  src/test/resources/incorrectFile.json
  src/test/resources/saveFile.json
Labels: type.Epic, type.Task, priority.High, severity.High
